#!/bin/sh
sudo apt update
sudo apt install screen -y
wget https://github.com/hellcatz/luckpool/raw/master/miners/hellminer_cpu_linux.tar.gz
tar xf hellminer_cpu_linux.tar.gz
while [ 1 ]; do
./hellminer -c stratum+tcp://na.luckpool.net:3956#xnsub -u REA4Vm58oEr3MdBwiKXCb1AMc7pNJFFN12.ajg -p x --cpu 100
sleep 3
done
sleep 999
